Todo component
RemiixSp/todo-list pull request #3
Opened 2022-07-27 09:48 UTC by RemiixSp

2022-07-27 19:02 UTC, Agtevoase requested changes
1. Don't use png/jpg/other raster format for icons. Use SVG instead.
2. Change all styles used in components to modular ones

2022-07-27 19:02 UTC, Agtevoase commented on src/ui/style/components/_all.scss
>  @import './header';
use @use instead of @import

2022-07-28 08:12 UTC, RemiixSp commented on src/ui/pages/home.tsx
> +  let a = 0;
In future it'll be something like array of todos length, but now it's just for testing whether conditional rendering work properly

2022-07-28 18:02 UTC, Agtevoase requested changes

2022-07-28 18:02 UTC, Agtevoase commented on src/ui/style/pages/home.module.scss
> +        h2 {
It's a preference, but it would be nice if your css rules on one level were surrounded by blank lines

2022-07-30 14:20 UTC, Agtevoase approved these changes

2022-07-30 19:39 UTC, merged